### ISSUE TITLE
Ensure that directories exist before qsub

### ISSUE THREAD

**Issue by pb-cdunn** [PacificBiosciences/pypeFLOW#27]
I'm not sure yet whether this is about the directory passed to the qsub command, or a directory which we cd into within a script running on a new host, but @flowers9 has definitely found that some jobs fail immediately because directories are not yet available. (See https://github.com/PacificBiosciences/FALCON/issues/433#issuecomment-243333486 )

**Comment by mhsieh** [comment]
Can you be more specific about which directory might require a preflight check?

**Comment by flowers9** [comment]
mypwatcher/job/<job_directory>

They get created right before the related jobs get sent off to qsub, and a number of them can end up in an errored state in grid because grid can't find the directory when it tries to launch the job on a remote machine.

That said, even after I got rid of those directories with my patch, the same thing also sometime happened with the 0-rawreads/job_* directories, and falcon does the same thing there where it first launches the dalign jobs (i.e., create all the job_* directories and then launch a bunch of processes that need to run in them).

In general, I would suggest creating the directories on the remote machine (in the script that gets run) to ensure they exist.

**Comment by pb-cdunn** [comment]
MJ, I've already solved this on the `blocking` branch in a very simple way.

Unfortunately, management has not decided whether that is a Sprint task or an emergency for Goat/3.2. Let's coordinate in Slack.

**Comment by pb-cdunn** [comment]
This is frustrating. We cannot generate the top-level script because then it might not exist yet (with executable permission) on the remote host. (That is the point of this Issue.) But we cannot pass arguments because pbsmrtpipe gives us this start_tmpl:

```js
{
        "start": "qsub -S /bin/bash -sync y -V -q production -N ${JOB_ID} \\\n    -o \"${STDOUT_FILE}\" \\\n    -e \"${STDERR_FILE}\" \\\n    -pe smp ${NPROC} \\\n    \"${CMD}\""
}
```
If we put arguments into `$CMD`, then bash says "unable to find script".

Possible solution: Pass the arguments via the shell environment, which should always be passed via cluster-submission.

**Comment by pb-cdunn** [comment]
This is solved only when using the new "blocking" pwatcher, which requires `job_type=string` and `job_queue=CMD`. That will eventually be the default, when we get integration problems worked out.
